export const TYPECHECK_OUTPUT = `1  components/BaseDialogConfirmDeletion.vue:98
1  components/BaseDrawflowCanvas.vue:45
1  components/BaseGroupAssetExplainText.vue:2
1  components/CollectionCreateStepperAddAssets.vue:34
1  components/CollectionCreateStepperMetadataForm.vue:185
2  components/CollectionDetailsAssetTables.vue:25
4  components/CollectionListAssetsTable.vue:61
3  components/DataAddDataCoverage.vue:89
8  components/DataAddDataOwnership.vue:10
6  components/DataAddDataPanelProgress.vue:21
8  components/DataAddDataReviewAndConfirm.vue:74
9  components/DataAddDataStepper.vue:67
4  components/DataCatalogueSummaryBox.vue:22
5  components/DrawflowStepNode.vue:18
1  components/DrawflowStepNodeLoop.vue:21
6  components/DrawflowStepNodeSelectAsset.vue:59
7  components/GroupAddAssetsDataSelector.vue:61
4  components/GroupAddAssetsModelsWorkflowsSelector.vue:90
1  components/GroupAddAssetsSetPermissions.vue:43
2  components/GroupAddAssetsStepper.vue:57
3  components/GroupAssetEditPermissionsDialog.vue:4
10  components/GroupAssetsDatasetsTable.vue:68
5  components/GroupAssetsModelsWorkflowsTable.vue:98
2  components/GroupCreate.vue:48
2  components/GroupDetailsAssets.vue:67
4  components/GroupDetailsUsers.vue:151
6  components/GroupEdit.vue:25
1  components/GroupRolesTable.vue:87
6  components/ModelAddUploadPanelProgress.vue:24
2  components/VisualisationCatalogue.vue:188
7  components/VisualisationCreateStepperDataSelector.vue:54
4  components/VisualisationCreateStepperMetadataForm.vue:77
1  components/VisualisationDetailsAssets.vue:16
9  components/WorkflowBuilderStepper.vue:29
4  components/WorkflowBuilderStepperDraggableStepList.vue:23
3  components/WorkflowBuilderStepperPublishStepMetadata.vue:12
1  components/WorkflowBuilderStepperStepEntry.vue:16
4  components/__tests__/AccountDetailsAccountStatusExpert.test.ts:68
6  components/__tests__/AccountUpgradeForm.test.ts:202
1  components/__tests__/BaseButtonCopyToClipboard.test.ts:73
2  components/__tests__/BaseCatalogueFilterCard.test.ts:239
1  components/__tests__/BaseCatalogueSummaryBox.test.ts:44
1  components/__tests__/BaseDafniIdentifiers.test.ts:89
13  components/__tests__/BaseDetailsSectionDetails.test.ts:78
14  components/__tests__/BaseDetailsVersionBar.test.ts:152
1  components/__tests__/BaseDialogConfirm.test.ts:54
23  components/__tests__/BaseDialogConfirmDeletion.test.ts:44
31  components/__tests__/BaseFileDrop.test.ts:62
7  components/__tests__/BaseHelpMenuPopover.test.ts:44
2  components/__tests__/BaseLeafletMap.test.ts:43
3  components/__tests__/BaseLicenceField.test.ts:54
2  components/__tests__/BaseVersionSelect.test.ts:18
44  components/__tests__/BaseVersionsListTable.test.ts:64
6  components/__tests__/CollectionAddAssetsTable.test.ts:75
39  components/__tests__/CollectionCreateStepper.test.ts:103
7  components/__tests__/CollectionCreateStepperAddAssets.test.ts:94
2  components/__tests__/CollectionCreateStepperAddImages.test.ts:238
32  components/__tests__/CollectionCreateStepperMetadataForm.test.ts:70
5  components/__tests__/CollectionDetailsAssetTables.test.ts:67
4  components/__tests__/CollectionListAssetsTable.test.ts:77
5  components/__tests__/CollectionsCatalogueIterator.test.ts:43
6  components/__tests__/DataAddDataAdditionalMetadata.test.ts:50
12  components/__tests__/DataAddDataBasicMetadata.test.ts:49
83  components/__tests__/DataAddDataCoverage.test.ts:93
8  components/__tests__/DataAddDataCoverageGeojsonEditor.test.ts:69
4  components/__tests__/DataAddDataCoverageGeonamesItem.test.ts:58
5  components/__tests__/DataAddDataEntry.test.ts:80
32  components/__tests__/DataAddDataOwnership.test.ts:77
2  components/__tests__/DataAddDataPanelProgress.test.ts:23
8  components/__tests__/DataAddDataProjectMetadata.test.ts:50
2  components/__tests__/DataAddDataReviewAndConfirm.test.ts:40
117  components/__tests__/DataAddDataStepper.test.ts:179
2  components/__tests__/DataCatalogueFilterCardDateRange.test.ts:67
1  components/__tests__/DataCatalogueIterator.test.ts:221
4  components/__tests__/DataCatalogueSummaryBox.test.ts:44
1  components/__tests__/DataDetailsActionsButton.test.ts:157
43  components/__tests__/DataDetailsSectionDataFiles.test.ts:123
1  components/__tests__/DrawflowStepNode.test.ts:249
6  components/__tests__/DrawflowStepNodeLoop.test.ts:82
6  components/__tests__/DrawflowStepNodeModel.test.ts:59
36  components/__tests__/DrawflowStepNodeSelectAsset.test.ts:76
44  components/__tests__/GroupAddAssetsDataSelector.test.ts:28
37  components/__tests__/GroupAddAssetsModelsWorkflowsSelector.test.ts:27
7  components/__tests__/GroupAddAssetsSetPermissions.test.ts:35
29  components/__tests__/GroupAddAssetsStepper.test.ts:46
10  components/__tests__/GroupAssetEditPermissionsDialog.test.ts:87
15  components/__tests__/GroupAssetsDatasetsTable.test.ts:116
22  components/__tests__/GroupAssetsModelsWorkflowsTable.test.ts:121
10  components/__tests__/GroupCatalogue.test.ts:30
13  components/__tests__/GroupCreate.test.ts:34
1  components/__tests__/GroupDetailsActionsButton.test.ts:42
7  components/__tests__/GroupDetailsAssets.test.ts:50
1  components/__tests__/GroupDetailsSectionDetails.test.ts:35
19  components/__tests__/GroupDetailsUsers.test.ts:60
20  components/__tests__/GroupEdit.test.ts:42
4  components/__tests__/GroupRolesTable.test.ts:42
1  components/__tests__/HomePageHighlightCard.test.ts:61
1  components/__tests__/HomePageSectionReleaseNotes.test.ts:87
28  components/__tests__/ModelAddUploadPanel.test.ts:150
1  components/__tests__/ModelAddUploadPanelDataDrop.test.ts:85
1  components/__tests__/ModelDetailsActionsButton.test.ts:159
10  components/__tests__/ModelDetailsSectionInputDataSlots.test.ts:85
14  components/__tests__/ModelDetailsSectionInputParameters.test.ts:85
18  components/__tests__/ModelDetailsSectionOutputFiles.test.ts:54
28  components/__tests__/ModelEditUploadPanel.test.ts:164
22  components/__tests__/VisualisationCatalogue.test.ts:189
38  components/__tests__/VisualisationCreateStepper.test.ts:53
44  components/__tests__/VisualisationCreateStepperDataSelector.test.ts:21
17  components/__tests__/VisualisationCreateStepperMetadataForm.test.ts:21
4  components/__tests__/VisualisationDetailsActionsButton.test.ts:163
2  components/__tests__/VisualisationDetailsAssets.test.ts:53
4  components/__tests__/VisualisationDetailsSectionDetails.test.ts:30
7  components/__tests__/VisualisationEdit.test.ts:24
4  components/__tests__/VisualisationTypeCard.test.ts:67
2  components/__tests__/WorkflowBuilderStepper.NavigationGuard.test.ts:40
47  components/__tests__/WorkflowBuilderStepper.test.ts:44
3  components/__tests__/WorkflowBuilderStepperDraggableStepList.test.ts:70
20  components/__tests__/WorkflowBuilderStepperParameterSetMetadataForm.test.ts:48
131  components/__tests__/WorkflowBuilderStepperPublishStepMetadata.test.ts:54
9  components/__tests__/WorkflowBuilderStepperStepEntry.test.ts:107
25  components/__tests__/WorkflowBuilderStepperWorkflowMetadataForm.test.ts:48
3  components/__tests__/WorkflowCatalogueIterator.test.ts:116
22  components/__tests__/WorkflowDetailsSectionParameterSets.test.ts:256
22  layouts/__tests__/default.test.ts:56
1  pages/account/index.vue:96
5  pages/collections/__tests__/create.test.ts:44
22  pages/collections/__tests__/details.test.ts:54
7  pages/collections/__tests__/index.test.ts:52
5  pages/collections/__tests__/owned.test.ts:47
1  pages/collections/details.vue:31
5  pages/data/__tests__/add.test.ts:41
45  pages/data/__tests__/details.test.ts:104
15  pages/data/__tests__/edit.test.ts:26
9  pages/data/__tests__/versions.test.ts:54
8  pages/data/details.vue:63
3  pages/data/edit.vue:50
1  pages/data/versions.vue:40
17  pages/groups/__tests__/add.test.ts:74
5  pages/groups/__tests__/create.test.ts:43
58  pages/groups/__tests__/details.test.ts:76
19  pages/groups/__tests__/edit.test.ts:29
1  pages/groups/__tests__/index.test.ts:106
2  pages/groups/add.vue:35
9  pages/groups/details.vue:54
7  pages/groups/edit.vue:37
5  pages/models/__tests__/add.test.ts:34
39  pages/models/__tests__/details.test.ts:61
17  pages/models/__tests__/edit.test.ts:29
1  pages/models/__tests__/index.test.ts:32
9  pages/models/__tests__/versions.test.ts:54
5  pages/models/details.vue:69
2  pages/models/edit.vue:37
1  pages/models/versions.vue:40
5  pages/visualisations/__tests__/create.test.ts:43
25  pages/visualisations/__tests__/details.test.ts:31
15  pages/visualisations/__tests__/edit.test.ts:23
3  pages/visualisations/details.vue:52
3  pages/visualisations/edit.vue:35
39  pages/workflows/__tests__/details.test.ts:125
2  pages/workflows/__tests__/index.test.ts:28
9  pages/workflows/__tests__/versions.test.ts:54
3  pages/workflows/details.vue:64
1  pages/workflows/versions.vue:40
3  stores/__tests__/accountUpgrade.test.ts:41
20  stores/__tests__/collectionCreate.test.ts:190
1  stores/__tests__/collectionDetails.test.ts:62
20  stores/__tests__/dataAddData.test.ts:233
18  stores/__tests__/dataCatalogue.test.ts:118
1  stores/__tests__/dataCatalogueFilters.test.ts:31
2  stores/__tests__/dataDetails.test.ts:120
9  stores/__tests__/drawflow.test.ts:86
26  stores/__tests__/geonames.test.ts:61
1  stores/__tests__/groupAddAssets.test.ts:74
4  stores/__tests__/groupCreate.test.ts:42
12  stores/__tests__/groupDetails.test.ts:90
2  stores/__tests__/modalDialogs.test.ts:105
237  stores/__tests__/modelCatalogue.test.ts:53
15  stores/__tests__/modelCatalogueFilters.test.ts:31
8  stores/__tests__/modelDetails.test.ts:63
6  stores/__tests__/roleCatalogue.test.ts:68
6  stores/__tests__/visualisationCreate.test.ts:107
91  stores/__tests__/workflowBuilder.test.ts:124
190  stores/__tests__/workflowCatalogue.test.ts:50
13  stores/__tests__/workflowCatalogueFilters.test.ts:31
2  stores/__tests__/workflowDetails.test.ts:66
16  stores/dataAddData.ts:34
1  stores/dataCatalogue.ts:78
5  stores/drawflow.ts:195
11  stores/geonames.ts:24
1  stores/groupCreate.ts:17
2  stores/modelCatalogue.ts:203
1  stores/modelCatalogueFilters.ts:30
1  stores/modelDetails.ts:100
1  stores/roleCatalogue.ts:60
1  stores/visualisationCreate.ts:57
30  stores/workflowBuilder.ts:13
2  stores/workflowCatalogue.ts:170
1  stores/workflowCatalogueFilters.ts:26
1  stores/workflowDetails.ts:56
3  ts/__tests__/apiCallUtils.test.ts:122
42  ts/__tests__/catalogueFiltersUtils.test.ts:49
11  ts/__tests__/drawflowOverride.test.ts:48
6  ts/__tests__/formRules.test.ts:73
5  ts/__tests__/helpers.test.ts:118
1  ts/__tests__/imageValidation.test.ts:30
27  ts/__tests__/keycloakIntegration.test.ts:34
6  ts/__tests__/leafletMap.test.ts:114
4  ts/__tests__/versionHistoryUtils.test.ts:8
2  ts/apiCallUtils.ts:102
1  ts/catalogueFiltersUtils.ts:112
6  ts/dataMetadataFactoryFunctions.ts:1
44  ts/drawflowOverride.ts:9
4  ts/helpers.ts:41
1  ts/keycloak.mock.ts:37
1  ts/keycloakIntegration.mock.ts:13
3  ts/keycloakIntegration.ts:90
1  ts/leafletMap.ts:73
27  ts/testData.ts:243
1  ts/versionHistoryUtils.ts:7
3  ts/workflowFactoryFunctions.ts:30
1  vitest.config.ts:16`

export interface TypecheckResult {
  filePath: string
  errors: number
}

export const TYPECHECK_RESULTS: TypecheckResult[] = TYPECHECK_OUTPUT.split('\n').map(line => {
  const [count, filePath] = line.split('  ')
  return { filePath, errors: parseInt(count, 10) }
})